<?php
/**
 * Plugin Name: My Custom Styles
 * Plugin URI: https://github.com/ArthurGareginyan/my-custom-styles
 * Description: Easily and safely add your custom styles (CSS) to WordPress website's HEAD section directly out of your WordPress Dashboard without need of an external editor.
 * Author: Arthur Gareginyan
 * Author URI: http://www.arthurgareginyan.com
 * Version: 3.2
 * License: GPL3
 * Text Domain: my-custom-styles
 * Domain Path: /languages/
 *
 * Copyright 2015-2016 Arthur Gareginyan (email : arthurgareginyan@gmail.com)
 *
 * This file is part of "My Custom Styles".
 *
 * "My Custom Styles" is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * "My Custom Styles" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with "My Custom Styles".  If not, see <http://www.gnu.org/licenses/>.
 *
 */


/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Define global constants
 *
 * @since 3.1
 */
defined('MCSTYLES_DIR') or define('MCSTYLES_DIR', dirname(plugin_basename(__FILE__)));
defined('MCSTYLES_BASE') or define('MCSTYLES_BASE', plugin_basename(__FILE__));
defined('MCSTYLES_URL') or define('MCSTYLES_URL', plugin_dir_url(__FILE__));
defined('MCSTYLES_PATH') or define('MCSTYLES_PATH', plugin_dir_path(__FILE__));
defined('MCSTYLES_VERSION') or define('MCSTYLES_VERSION', '3.1');

/**
 * Register text domain
 *
 * @since 2.1
 */
function mcstyles_textdomain() {
	load_plugin_textdomain( 'my-custom-styles', false, MCSTYLES_DIR . '/languages/' );
}
add_action( 'init', 'mcstyles_textdomain' );

/**
 * Print direct link to Custom Styles admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the Custom Styles admin page
 *
 * @since  2.1
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function mcstyles_settings_link( $links ) {
	$settings_page = '<a href="' . admin_url( 'themes.php?page=my-custom-styles.php' ) .'">' . __( 'Settings', 'my-custom-styles' ) . '</a>';
	array_unshift( $links, $settings_page );
	return $links;
}
add_filter( "plugin_action_links_".MCSTYLES_BASE, 'mcstyles_settings_link' );

/**
 * Register "Custom Styles" submenu in "Appearance" Admin Menu
 *
 * @since 2.1
 */
function mcstyles_register_submenu_page() {
	add_theme_page( __( 'My Custom Styles', 'my-custom-styles' ), __( 'Custom Styles', 'my-custom-styles' ), 'edit_theme_options', basename( __FILE__ ), 'mcstyles_render_submenu_page' );
}
add_action( 'admin_menu', 'mcstyles_register_submenu_page' );

/**
 * Attach Settings Page
 *
 * @since 3.0
 */
require_once( MCSTYLES_PATH . 'inc/php/settings_page.php' );

/**
 * Register settings
 *
 * @since 0.1
 */
function mcstyles_register_settings() {
	register_setting( 'mcstyles_settings_group', 'mcstyles_settings' );
}
add_action( 'admin_init', 'mcstyles_register_settings' );

/**
 * Load scripts and style sheet for settings page
 *
 * @since 3.1
 */
function mcstyles_load_scripts($hook) {

    // Return if the page is not a settings page of this plugin
    if ( 'appearance_page_my-custom-styles' != $hook ) {
        return;
    }

    // Style sheet
    wp_enqueue_style( 'mcstyles-admin-css', MCSTYLES_URL . 'inc/css/admin.css' );

    // JavaScript
    wp_enqueue_script( 'mcstyles-admin-js', MCSTYLES_URL . 'inc/js/admin.js' );

    // CodeMirror
    wp_enqueue_style( 'mcstyles-codemirror-css', MCSTYLES_URL . 'inc/lib/codemirror/codemirror.css' );
    wp_enqueue_script( 'mcstyles-codemirror-js', MCSTYLES_URL . 'inc/lib/codemirror/codemirror-compressed.js' );
    wp_enqueue_script( 'mcstyles-codemirror-active-line', MCSTYLES_URL . 'inc/lib/codemirror/addons/active-line.js' );

}
add_action( 'admin_enqueue_scripts', 'mcstyles_load_scripts' );

/**
 * Include custom CSS in HEAD section
 *
 * @since 2.3
 */
function mcstyles_add_styling() {

    // Read variables from DB
    $options = get_option( 'mcstyles_settings' );
    $content = isset( $options['mcstyles-content'] ) && !empty( $options['mcstyles-content'] ) ? $options['mcstyles-content'] : ' ';
    $enable = isset( $options['enable'] ) && !empty( $options['enable'] ) ? $options['enable'] : ' ';

    // If the user entered code is disabled...
    if ( $enable == 'on') {
        return;   // EXIT
    }

    // If content is empty...
    if ( empty($content) OR $content == ' ' ) {
        return;   // EXIT
    }

    // Cleaning
    $content = trim( $content );

    // Prepare the user entered code for execution
    $contents_out = '<style type="text/css">' . "\n";
    $contents_out .= $content . "\n";
    $contents_out .= '</style>' . "\n";

    // Return prepared code
    echo $contents_out;
}
add_action( 'wp_head', 'mcstyles_add_styling' );

/**
 * Delete options on uninstall
 *
 * @since 0.1
 */
function mcstyles_uninstall() {
    delete_option( 'mcstyles_settings' );
}
register_uninstall_hook( __FILE__, 'mcstyles_uninstall' );

?>